Python bindings
robotology/superquadric-lib pull request #32
Opened 2020-07-21 10:19 UTC by eleramp

This PR adds the python bindings for the library. Bindings are generated with SWIG.

2020-07-22 10:42 UTC, pattacini requested changes
Thanks @eleramp for the nice additions.

There are a few files where you've just touched the formatting.
Could you please rule them out from this PR for the sake of cleanness?

2020-07-27 09:56 UTC, pattacini commented
@eleramp since I've noticed that you're still working out the PR, I've made it a draft.
When you're ready, you could turn it back into a normal PR, triggering me.

2020-07-27 10:13 UTC, eleramp commented
Thank @pattacini for reviewing this PR!
I removed the commit about the code formatting, as you asked.

2020-07-27 10:15 UTC, pattacini approved these changes

2020-07-27 10:23 UTC, merged